### ISSUE TITLE
mistake in picture?

### ISSUE THREAD

**Issue by lihuiliullh** [jeffhj/domain-relevance#1]
Hi Jie, is there a mistake in the following picture?
According to section 3.1 in the paper, given a seed node, it will connect with 2k core nodes. This graph is called term graph. But in the picture, all the core nodes are connected together. may i know why they are connected?

![image](https://user-images.githubusercontent.com/53407011/153780310-baaf843e-ebee-45b6-bf9b-8018f7b4adba.png)

**Comment by jeffhj** [comment]
Hi Lihui, thanks for your interest!

Seed terms include both core and fringe terms (any term can be a query), so core terms can also be connected to other core terms.

Feel free to keep asking if you have any other questions :)
